"""Real-data analysis: ETTh1, ECL, and dataset correlation characterisation.

Reads
-----
results/results_etth1.csv             Required. ETTh1 CI vs CD per-seed,
    matched-budget protocol (batch=32 both modes, warmup=10 both, min_epochs=15),
    five seeds {42, 123, 456, 789, 1011}.
    Required columns: mode, pred_len, seed, test_mse, best_epoch.
    Optional budget columns: steps_per_epoch, total_steps_to_best.

results/results_ecl.csv        Optional. ECL per-seed results, CI and CD.
    Required columns: mode, pred_len, seed, test_mse.
    If an arch_version column is present, every row must carry the value 2;
    the script raises otherwise. Modes, horizons, and seeds are taken from the
    file rather than assumed, and the summary and figure adapt to what is
    present. If absent, the ECL panel is omitted and the figure is incomplete
    for submission.

results/realdata_corr_summary.csv         Optional. Pre-computed per-dataset
    lag-0 and lag-structure summary. Produced by
    src/analysis/measure_lag_structure.py, which must be run first; this
    script does not compute correlation statistics itself, only reports and
    verifies them.
    Required columns: dataset, lag0_mean_abs_r, lag0_median_abs_r,
    mean_max_over_lags, pct_pairs_gain_ge_5pct_from_lags.

results/realdata_lag_summary.csv          Optional. Mean abs cross-correlation
    at each lag per dataset, from the same upstream script. Required columns:
    dataset, lag, mean_abs_r.

Writes
------
paper/figures/real_data.png
    Left panel: ETTh1 CI vs CD bar chart across horizons {96, 192, 336, 720}.
    Right panel (if ECL available): ECL bar chart over the modes and horizons
    present in the file. Error bars are drawn only where a group has two or
    more seeds; single-seed groups are plotted without error bars and the
    panel title states the seeds used.

Console
-------
ETTh1 ratio table; per-horizon paired CD-CI differences with 95% t-CIs;
budget-match verification table (CD/CI steps_per_epoch ratio equals 1.0);
ECL summary; dataset correlation characterisation (descriptive, with explicit
heuristic disclaimer) with an oracle check against the values quoted in
main.tex Section 3.2.

Statistical notes
-----------------
ETTh1 uses a budget matched across modes: batch size 32 and warmup_epochs 10 for both CI and CD, with a 15-epoch
minimum before early stopping. CI and CD therefore run an identical number of gradient updates per epoch at each
horizon, so neither the step count nor the warmup schedule can account for any CI-CD difference. The earlier
confounded run (ci_cd_etth1_raw_with_budget.csv: CI batch 128 vs CD batch 32, CI warmup 10 vs CD warmup 2) is retired.

With n=5 seeds per horizon (df=4, t-critical=2.776) the paired CD-CI differences are tested per horizon and pooled.
CD never attains a significant advantage; CI is significantly better at H=96 and H=720, and the pooled difference
favours CI. The step-count table below verifies the budget match (CD/CI steps_per_epoch ratio equals 1.0) rather than
documenting an asymmetry.

ECL results are descriptive. Confidence intervals and significance tests are
reported only for groups with at least two seeds; a single-seed group is
reported as point estimates with the seed identified.

Correlation summary provenance: realdata_corr_summary.csv is regenerated by
src/analysis/measure_lag_structure.py whenever the underlying data split
changes (in particular, the ECL train_rows value must match the paper's
proportional 60/20/20 split, currently 15,813). This script cross-checks the
loaded summary against a pinned oracle (_ORACLE_CORR below) and reports
PASS/FAIL per dataset rather than trusting an unreviewed run. Before the
oracle has been pinned for the first time, it prints the computed values as
UNVERIFIED and does not fail the run; a human must review those values
against main.tex and pin them before the corresponding paper numbers are
treated as confirmed.

Usage
-----
uv run src/analysis/analyze_realdata.py [path/to/results_etth1.csv]
Run from the repository root; all paths resolve relative to it.
"""

import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy import stats

plt.rcParams.update(
    {
        "font.family": "serif",
        "font.size": 10,
        "axes.titlesize": 11,
        "axes.labelsize": 10,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "savefig.dpi": 300,
        "pdf.fonttype": 42,
        "ps.fonttype": 42,
    }
)

_ROOT = Path(__file__).resolve().parents[2]
_RESULTS_DIR = _ROOT / "results"
_FIGURES_DIR = _ROOT / "paper" / "figures"

_ETTH1_PATH = _RESULTS_DIR / "results_etth1.csv"
_ECL_PATH = _RESULTS_DIR / "results_ecl.csv"
_CORR_PATH = _RESULTS_DIR / "realdata_corr_summary.csv"
_LAG_PATH = _RESULTS_DIR / "realdata_lag_summary.csv"

_CI_COLOR = "#0072b2"  # blue  (Wong 2011 colourblind-safe palette)
_CD_COLOR = "#d55e00"  # vermillion

_BUDGET_COLS: frozenset[str] = frozenset({"steps_per_epoch", "total_steps_to_best"})
_ECL_ARCH_VERSION = 2  # Architecture revision matching the committed models.py.

# Oracle targets for realdata_corr_summary.csv, quoted from main.tex Section 3.2
# ("Correlation and lead-lag structure"). Each tuple is
# (lag0_mean_abs_r, lag0_median_abs_r, mean_max_over_lags, pct_pairs_gain).
# Pinned from a run against the current data files under the corrected ECL
# split (train_rows=15813, fixing an earlier 15,840 row-count error in the
# now-retired sandbox version of measure_lag_structure.py). Verified by hand
# against main.tex on 18 Aug 2026: every figure the paper states rounds to
# these values at the precision it reports them, so the earlier row-count
# error did not change any number actually printed in the paper.
_ORACLE_CORR: dict[str, tuple[float, float, float, float] | None] = {
    "ETTh1": (0.311013, 0.232797, 0.349276, 42.86),
    "ECL": (0.502687, 0.482602, 0.596492, 49.09),
}
_ORACLE_TOLERANCE = 1e-4


# ── Data loading ──────────────────────────────────────────────────────────────


def _load_optional(path: Path, required: set[str], label: str) -> pd.DataFrame | None:
    """Load a CSV if it exists; return None with a notice if it does not."""
    if not path.exists():
        print(f"[SKIP] {label} not found: {path}")
        return None
    df = pd.read_csv(path)
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"{label} missing columns: {missing}")
    return df


def load_etth1(path: Path) -> pd.DataFrame:
    required = {"mode", "pred_len", "seed", "test_mse", "best_epoch"}
    df = _load_optional(path, required, "ETTh1 results")
    if df is None:
        raise FileNotFoundError(f"ETTh1 results are required but not found: {path}")
    return df


def load_ecl(path: Path) -> pd.DataFrame | None:
    """Load ECL results, validating modes, uniqueness, and architecture version.

    Both CI and CD rows are accepted. When an arch_version column is present,
    every row must equal _ECL_ARCH_VERSION so that results from the retired
    pre-correction architecture cannot enter the analysis unnoticed.
    """
    df = _load_optional(path, {"mode", "pred_len", "seed", "test_mse"}, "ECL results")
    if df is None:
        return None
    bad_modes = set(df["mode"]) - {"CI", "CD"}
    if bad_modes:
        raise ValueError(f"ECL results contain unexpected modes: {sorted(bad_modes)}")
    dup = df.duplicated(subset=["mode", "pred_len", "seed"])
    if dup.any():
        raise ValueError(
            f"ECL results contain {int(dup.sum())} duplicate (mode, pred_len, seed) rows."
        )
    if "arch_version" in df.columns:
        versions = set(df["arch_version"].unique().tolist())
        if versions != {_ECL_ARCH_VERSION}:
            raise ValueError(
                f"ECL arch_version must be {{{_ECL_ARCH_VERSION}}}; found {sorted(versions)}."
            )
    return df


def load_corr_summary(path: Path) -> pd.DataFrame | None:
    required = {
        "dataset",
        "lag0_mean_abs_r",
        "lag0_median_abs_r",
        "mean_max_over_lags",
        "pct_pairs_gain_ge_5pct_from_lags",
    }
    return _load_optional(path, required, "Correlation summary")


def load_lag_summary(path: Path) -> pd.DataFrame | None:
    return _load_optional(path, {"dataset", "lag", "mean_abs_r"}, "Lag summary")


# ── Aggregation ───────────────────────────────────────────────────────────────


def aggregate_by_mode_horizon(df: pd.DataFrame) -> pd.DataFrame:
    """Mean, std, and seed count of test_mse per (mode, pred_len).

    std uses ddof=1 and is therefore NaN for single-seed groups; downstream
    consumers treat NaN as "no dispersion estimate" rather than zero.
    """
    return (
        df.groupby(["mode", "pred_len"])["test_mse"]
        .agg(mse_mean="mean", mse_std="std", n="count")
        .reset_index()
    )


def mode_comparison_table(df: pd.DataFrame) -> pd.DataFrame:
    """Per-horizon CI vs CD means with CD/CI ratio and CD-CI difference.

    Horizons present in only one mode are dropped from the comparison; they
    still appear in the per-mode aggregate and the figure.
    """
    agg = aggregate_by_mode_horizon(df)
    ci = agg[agg["mode"] == "CI"][["pred_len", "mse_mean", "n"]].rename(
        columns={"mse_mean": "ci", "n": "n_ci"}
    )
    cd = agg[agg["mode"] == "CD"][["pred_len", "mse_mean", "n"]].rename(
        columns={"mse_mean": "cd", "n": "n_cd"}
    )
    merged = ci.merge(cd, on="pred_len")
    merged["ratio"] = merged["cd"] / merged["ci"]
    merged["diff"] = merged["cd"] - merged["ci"]
    merged["rel_pct"] = 100.0 * merged["diff"] / merged["ci"]
    return merged.sort_values("pred_len").reset_index(drop=True)


def etth1_ratio_table(df: pd.DataFrame) -> pd.DataFrame:
    """CD/CI MSE ratio per horizon."""
    return mode_comparison_table(df)[["pred_len", "ci", "cd", "ratio"]]


def etth1_paired_diff(df: pd.DataFrame) -> pd.DataFrame:
    """Per-horizon CD-CI paired differences, matched by seed.

    Returns one row per pred_len with columns:
        pred_len, mean_diff, std_diff, ci_lo, ci_hi, signs, rel_pct, ci_mean.

    t-critical uses df = n_seeds - 1 (n=5 gives df=4, t=2.776). The budget is matched across modes,
    so the per-horizon CD-CI differences carry no step-count or warmup confound; CD never wins
    significantly and CI is significantly better at H=96 and H=720.
    """
    pivot = (
        df[df["mode"].isin(["CI", "CD"])]
        .pivot_table(index=["pred_len", "seed"], columns="mode", values="test_mse")
        .dropna()
        .reset_index()
    )
    pivot["diff"] = pivot["CD"] - pivot["CI"]

    rows: list[dict] = []
    for H, grp in pivot.groupby("pred_len"):
        d = grp["diff"].values
        n = len(d)
        mean_d = float(d.mean())
        std_d = float(d.std(ddof=1))
        se = std_d / np.sqrt(n)
        tcrit = stats.t.ppf(0.975, df=n - 1)
        ci_mean = float(grp["CI"].mean())
        rows.append(
            dict(
                pred_len=int(H),
                mean_diff=mean_d,
                std_diff=std_d,
                ci_lo=mean_d - tcrit * se,
                ci_hi=mean_d + tcrit * se,
                signs="".join("+" if x > 0 else ("-" if x < 0 else "0") for x in d),
                rel_pct=100.0 * mean_d / ci_mean,
                ci_mean=ci_mean,
            )
        )
    return pd.DataFrame(rows).sort_values("pred_len").reset_index(drop=True)


def etth1_budget_table(df: pd.DataFrame) -> pd.DataFrame:
    """Budget-match verification per (mode, pred_len). Returns empty if columns absent.

    Under the matched protocol CI and CD share batch size 32, so steps_per_epoch is identical across modes at each
    horizon and ratio_steps equals 1.0. The table documents this equality (the evidence that no step-count confound
    remains) rather than an asymmetry. total_steps_to_best may still differ because the two modes stop at different
    epochs; that is a convergence outcome, not a budget difference.
    """
    if not _BUDGET_COLS.issubset(df.columns):
        return pd.DataFrame()

    n_unique = df.groupby(["mode", "pred_len"])["steps_per_epoch"].nunique()
    if (n_unique > 1).any():
        bad = n_unique[n_unique > 1].index.tolist()
        raise ValueError(f"steps_per_epoch not constant within groups: {bad}")

    agg = (
        df.groupby(["mode", "pred_len"])
        .agg(
            steps_per_epoch=("steps_per_epoch", "first"),
            total_steps_mean=("total_steps_to_best", "mean"),
        )
        .reset_index()
    )
    ci = agg[agg["mode"] == "CI"][["pred_len", "steps_per_epoch", "total_steps_mean"]].rename(
        columns={"steps_per_epoch": "ci_spe", "total_steps_mean": "ci_total"}
    )
    cd = agg[agg["mode"] == "CD"][["pred_len", "steps_per_epoch", "total_steps_mean"]].rename(
        columns={"steps_per_epoch": "cd_spe", "total_steps_mean": "cd_total"}
    )
    merged = ci.merge(cd, on="pred_len")
    if (merged["ci_spe"] == 0).any():
        raise ValueError("ci_spe contains zero; cannot compute step ratio.")
    merged["ratio_steps"] = (merged["cd_spe"] / merged["ci_spe"]).round(1)
    return merged.sort_values("pred_len").reset_index(drop=True)


def etth1_pooled_diff(df: pd.DataFrame) -> dict:
    """Pooled CD-CI difference across all four horizons, clustered by seed.

    The same five seeds appear at every horizon, so naively pooling the 20
    (horizon, seed) pairs as independent draws understates the interval width.
    This averages each seed's CD-CI difference across the four horizons first,
    giving five genuinely independent units, then takes a paired t-CI over
    those -- the seed, not the (horizon, seed) pair, is the independent unit.

    Args:
        df: Raw long-format ETTh1 results (same input as etth1_paired_diff).

    Returns:
        Dict with mean, se, ci_lo, ci_hi, base_mean, n (seeds, not rows), rel_pct.

    Raises:
        ValueError: If any seed lacks a complete four-horizon CD/CI pair,
            since a silent partial average would change what "pooled" means
            without any signal that the input was incomplete.
    """
    pivot = (
        df[df["mode"].isin(["CI", "CD"])]
        .pivot_table(index=["pred_len", "seed"], columns="mode", values="test_mse")
        .dropna()
        .reset_index()
    )
    pivot["diff"] = pivot["CD"] - pivot["CI"]
    counts = pivot.groupby("seed").size()
    incomplete = counts[counts != 4]
    if not incomplete.empty:
        raise ValueError(
            f"Expected 4 horizons per seed with both CI and CD present; "
            f"seed(s) with a different count: {incomplete.to_dict()}"
        )
    per_seed = pivot.groupby("seed")["diff"].mean()
    n = len(per_seed)
    mean_d = float(per_seed.mean())
    se = float(per_seed.std(ddof=1) / np.sqrt(n))
    tcrit = float(stats.t.ppf(0.975, df=n - 1))
    base_mean = float(pivot["CI"].mean())
    return {
        "mean": mean_d, "se": se,
        "ci_lo": mean_d - tcrit * se, "ci_hi": mean_d + tcrit * se,
        "base_mean": base_mean, "n": n,
        "rel_pct": 100.0 * mean_d / base_mean,
    }


# Oracle values frozen against the committed results_etth1.csv (5 seeds, 4
# horizons). Clustered by seed per etth1_pooled_diff's docstring. mean/ci_lo/
# ci_hi to 4dp, rel_pct to 2dp.
_ORACLE_ETTH1_POOLED: dict[str, float] = {
    "mean": 0.0147, "ci_lo": 0.0000, "ci_hi": 0.0293, "rel_pct": 2.58,
}


def oracle_check_pooled(pooled: dict) -> bool:
    """Compare the freshly-computed pooled figures against the frozen oracle.

    Args:
        pooled: Output of etth1_pooled_diff.

    Returns:
        True if mean, ci_lo, ci_hi, and rel_pct all match the pinned oracle
        at the stated precision.
    """
    got = {
        "mean": round(pooled["mean"], 4), "ci_lo": round(pooled["ci_lo"], 4),
        "ci_hi": round(pooled["ci_hi"], 4), "rel_pct": round(pooled["rel_pct"], 2),
    }
    ok = got == _ORACLE_ETTH1_POOLED
    print(f"  [{'PASS' if ok else 'FAIL'}] pooled ETTh1: {got}"
          + ("" if ok else f" != oracle {_ORACLE_ETTH1_POOLED}"))
    return ok


# ── Console output ────────────────────────────────────────────────────────────


def print_etth1_summary(
    ratio: pd.DataFrame,
    paired: pd.DataFrame,
    budget: pd.DataFrame,
    seeds: list[int],
) -> None:
    """Print ETTh1 ratio table, paired differences, and budget-match verification."""
    seed_str = ", ".join(str(s) for s in seeds)
    print(f"\n=== ETTh1: CI vs CD MSE (mean over seeds {{{seed_str}}}) ===")
    print(f"{'H':>5}  {'CI':>8}  {'CD':>8}  {'CD/CI':>7}")
    print("-" * 36)
    for _, r in ratio.iterrows():
        print(f"{int(r.pred_len):>5}  {r.ci:>8.4f}  {r.cd:>8.4f}  {r.ratio:>7.4f}")

    print("\n=== ETTh1: per-horizon paired differences (CD - CI, matched by seed) ===")
    print("Positive = CD worse.")
    print(f"{'H':>5}  {'mean_diff':>10} {'rel_%':>8}  {'95%CI_lo':>10} {'95%CI_hi':>10}  sig  signs")
    print("-" * 70)
    for _, r in paired.iterrows():
        sig = "SIG" if (r.ci_lo > 0 or r.ci_hi < 0) else " ns"
        print(
            f"{int(r.pred_len):>5}  "
            f"{r.mean_diff:>+10.6f} {r.rel_pct:>+8.4f}%  "
            f"{r.ci_lo:>+10.6f} {r.ci_hi:>+10.6f}  {sig}  {r.signs}"
        )

    # Report significance direction programmatically, no confound narrative (budget is matched).
    sig_ci_better = [int(r.pred_len) for _, r in paired.iterrows() if r.ci_lo > 0]  # CD-CI>0 means CI better
    cd_wins = int((paired["mean_diff"] < 0).sum())
    print(
        f"\nBudget is matched across modes (batch 32, warmup 10 both). "
        f"CD achieves a lower mean than CI in {cd_wins} of {len(paired)} horizons; "
        f"no horizon shows a significant CD advantage. "
        f"CI is significantly better at H={sig_ci_better}. "
        f"With the per-epoch update count and warmup identical across modes, the "
        f"difference cannot be attributed to a compute or schedule asymmetry."
    )

    if not budget.empty:
        all_unity = bool((budget["ratio_steps"] == 1.0).all())
        print("\n=== ETTh1: budget-match verification ===")
        print(
            f"{'H':>5}  {'CI spe':>8}  {'CD spe':>8}  {'CD/CI':>7}  "
            f"{'CI total (mean)':>16}  {'CD total (mean)':>16}"
        )
        print("-" * 68)
        for _, r in budget.iterrows():
            print(
                f"{int(r.pred_len):>5}  {int(r.ci_spe):>8}  {int(r.cd_spe):>8}  "
                f"{r.ratio_steps:>7.1f}   {r.ci_total:>16.0f}  {r.cd_total:>16.0f}"
            )
        ratio_msg = (
            "1.0 at every horizon (confound removed)" if all_unity else "NOT all 1.0 -- check inputs"
        )
        print(
            f"Budget matched: warmup_epochs=10 and batch_size=32 for both modes. "
            f"steps_per_epoch ratio is {ratio_msg}."
        )


def print_etth1_pooled(pooled: dict) -> bool:
    """Print the seed-clustered pooled CD-CI summary and its oracle check.

    Args:
        pooled: Output of etth1_pooled_diff.

    Returns:
        True if the printed figures match the pinned oracle, else False --
        callers use this to gate the process exit code.
    """
    print("\n=== ETTh1: pooled CD-CI across all four horizons (clustered by seed, n=5) ===")
    print(
        f"Mean {pooled['mean']:+.4f} MSE ({pooled['rel_pct']:+.2f}% of CI mean), "
        f"95% CI [{pooled['ci_lo']:+.4f}, {pooled['ci_hi']:+.4f}]"
    )
    print("\n=== ORACLE CHECK ===")
    passed = oracle_check_pooled(pooled)
    print(f"RESULT: {'PASS' if passed else 'FAIL'}")
    return passed


def print_ecl_summary(ecl: pd.DataFrame) -> None:
    """Print ECL per-mode MSE and, where both modes exist, the CD-CI comparison.

    Inferential statistics require at least two seeds per group; below that,
    values are reported as descriptive point estimates with the seeds named.
    """
    seeds = sorted(int(s) for s in ecl["seed"].unique())
    modes = sorted(ecl["mode"].unique())
    seed_str = ", ".join(str(s) for s in seeds)
    print(f"\n=== ECL: test MSE by mode and horizon (seeds {{{seed_str}}}) ===")

    agg = aggregate_by_mode_horizon(ecl)
    print(f"{'mode':>5}  {'H':>5}  {'mean':>9}  {'std':>8}  {'n':>3}")
    print("-" * 38)
    for _, r in agg.sort_values(["pred_len", "mode"]).iterrows():
        std_str = f"{r.mse_std:>8.6f}" if np.isfinite(r.mse_std) else f"{'--':>8}"
        print(f"{r['mode']:>5}  {int(r.pred_len):>5}  {r.mse_mean:>9.6f}  {std_str}  {int(r.n):>3}")

    if {"CI", "CD"}.issubset(modes):
        comp = mode_comparison_table(ecl)
        print("\n--- CD vs CI (per horizon) ---")
        print(f"{'H':>5}  {'CI':>9}  {'CD':>9}  {'CD/CI':>7}  {'CD-CI':>9}  {'rel_%':>7}")
        print("-" * 56)
        for _, r in comp.iterrows():
            print(
                f"{int(r.pred_len):>5}  {r.ci:>9.6f}  {r.cd:>9.6f}  "
                f"{r.ratio:>7.4f}  {r['diff']:>+9.6f}  {r.rel_pct:>+7.2f}%"
            )
        min_n = int(min(comp["n_ci"].min(), comp["n_cd"].min()))
        if min_n < 2:
            print(
                f"Descriptive only: {min_n} seed per group, so no confidence "
                f"intervals or significance tests are reported."
            )
    else:
        print(f"Single mode present ({modes[0]}); no CD-CI comparison available.")


def check_corr_oracle(corr: pd.DataFrame) -> None:
    """Cross-check the loaded correlation summary against the pinned oracle.

    For each dataset with a pinned entry in _ORACLE_CORR, compares
    (lag0_mean_abs_r, lag0_median_abs_r, mean_max_over_lags, pct_gain) against
    the target within _ORACLE_TOLERANCE and reports PASS/FAIL. For a dataset
    with no pinned entry (value None), prints the computed values as
    UNVERIFIED instead of failing, since no reviewed target exists yet.

    Raises:
        ValueError: If a pinned oracle target does not match the loaded
            summary within tolerance.
    """
    pct_col = "pct_pairs_gain_ge_5pct_from_lags"
    print("\n=== Correlation summary: oracle check ===")
    for _, row in corr.iterrows():
        name = row["dataset"]
        target = _ORACLE_CORR.get(name)
        computed = (
            float(row["lag0_mean_abs_r"]),
            float(row["lag0_median_abs_r"]),
            float(row["mean_max_over_lags"]),
            float(row[pct_col]),
        )
        if target is None:
            print(
                f"  [UNVERIFIED] {name}: lag0_mean={computed[0]:.4f} "
                f"lag0_median={computed[1]:.4f} mean_max_over_lags={computed[2]:.4f} "
                f"pct_gain={computed[3]:.2f}% -- no oracle pinned; review by hand "
                f"against main.tex Section 3.2 before treating as confirmed."
            )
            continue
        deltas = [abs(c - t) for c, t in zip(computed, target)]
        if max(deltas) > _ORACLE_TOLERANCE:
            raise ValueError(
                f"{name}: correlation summary drifted from pinned oracle "
                f"(computed={computed}, target={target}, max delta={max(deltas):.6f})."
            )
        print(f"  [PASS] {name}: matches pinned oracle within {_ORACLE_TOLERANCE:g}.")


def print_corr_summary(corr: pd.DataFrame, lag: pd.DataFrame | None) -> None:
    """Print dataset correlation characterisation (descriptive only)."""
    print(
        "\n=== Dataset correlation characterisation (descriptive) ==="
        "\nThe 5pp gain threshold in 'pct_pairs_gain_ge_5pct_from_lags' is a "
        "heuristic reporting choice, not a statistically motivated cutoff."
    )
    for _, r in corr.iterrows():
        name = r["dataset"]
        gain = float(r["pct_pairs_gain_ge_5pct_from_lags"])
        lag0 = float(r["lag0_mean_abs_r"])
        max_lag = float(r["mean_max_over_lags"])
        print(f"\n{name}:")
        print(f"  Lag-0 mean |r|:                    {lag0:.4f}")
        print(f"  Lag-0 median |r|:                  {r['lag0_median_abs_r']:.4f}")
        print(f"  Mean max-over-lags |r|:            {max_lag:.4f}")
        print(f"  % pairs gaining >=5pp from lags:   {gain:.1f}%  (5pp threshold is heuristic)")

        if lag is not None:
            ds_lag = lag[lag["dataset"] == name]
            if not ds_lag.empty:
                lag0_r = float(ds_lag.loc[ds_lag["lag"] == 0, "mean_abs_r"].iloc[0])
                best = ds_lag.loc[ds_lag["mean_abs_r"].idxmax()]
                print(
                    f"  Best lag (highest mean |r|):        "
                    f"lag {int(best['lag'])} "
                    f"(mean |r|={best['mean_abs_r']:.4f}; lag-0={lag0_r:.4f})"
                )

    check_corr_oracle(corr)


# ── Figure ────────────────────────────────────────────────────────────────────


def _bar_yerr(rows: pd.DataFrame, pred_lens: list[int]) -> list[float] | None:
    """Error-bar values for one mode, or None when no group has a std estimate.

    A NaN std (single-seed group) is passed through as NaN, which matplotlib
    renders as an absent error bar; a zero would instead misrepresent the
    group as having zero measured dispersion.
    """
    vals = [float(rows.loc[p, "mse_std"]) if p in rows.index else np.nan for p in pred_lens]
    return None if all(np.isnan(v) for v in vals) else vals


def _draw_panel(
    ax: plt.Axes,
    agg: pd.DataFrame,
    pred_lens: list[int],
    title: str,
    ylabel: bool,
) -> None:
    """Grouped bar chart for one dataset over the modes present in agg.

    Correlation statistics are NOT overlaid on the bars: they are dataset-level
    descriptors while performance is horizon- and mode-specific. Combining them
    visually would insinuate a causal relationship not supported by the data.
    """
    bar_width = 0.35
    x = np.arange(len(pred_lens))

    ci_rows = agg[agg["mode"] == "CI"].set_index("pred_len")
    cd_rows = agg[agg["mode"] == "CD"].set_index("pred_len")
    show_cd = not cd_rows.empty

    def _vals(rows: pd.DataFrame, col: str) -> list[float]:
        return [float(rows.loc[p, col]) if p in rows.index else np.nan for p in pred_lens]

    if show_cd:
        ax.bar(
            x - bar_width / 2,
            _vals(ci_rows, "mse_mean"),
            bar_width,
            yerr=_bar_yerr(ci_rows, pred_lens),
            capsize=3,
            color=_CI_COLOR,
            alpha=0.88,
            label="CI",
            error_kw={"linewidth": 0.8},
        )
        ax.bar(
            x + bar_width / 2,
            _vals(cd_rows, "mse_mean"),
            bar_width,
            yerr=_bar_yerr(cd_rows, pred_lens),
            capsize=3,
            color=_CD_COLOR,
            alpha=0.88,
            label="CD",
            error_kw={"linewidth": 0.8},
        )
    else:
        ax.bar(
            x,
            _vals(ci_rows, "mse_mean"),
            bar_width * 1.4,
            yerr=_bar_yerr(ci_rows, pred_lens),
            capsize=3,
            color=_CI_COLOR,
            alpha=0.88,
            label="CI",
            error_kw={"linewidth": 0.8},
        )

    ax.set_xticks(x, labels=[str(p) for p in pred_lens])
    ax.set_xlabel("Prediction horizon", labelpad=4)
    if ylabel:
        ax.set_ylabel("Test MSE", labelpad=4)
    ax.set_title(title, pad=6)
    ax.legend(loc="upper left", framealpha=0.7)

    ci_means = _vals(ci_rows, "mse_mean")
    finite = [v for v in ci_means if not np.isnan(v)]
    if finite:
        ax.set_ylim(bottom=max(0.0, min(finite) * 0.92))
    ax.spines[["top", "right"]].set_visible(False)


def plot_real_data(
    etth1_agg: pd.DataFrame,
    ecl_agg: pd.DataFrame | None,
    ecl_seeds: list[int] | None,
    out_path: Path,
) -> None:
    """Generate the real-data bar chart figure.

    Takes pre-aggregated DataFrames (aggregation is the caller's
    responsibility). Left panel: ETTh1 CI vs CD. Right panel (if ECL): the
    modes and horizons present in the ECL file, with the seeds named in the
    title when fewer than two are available.
    """
    has_ecl = ecl_agg is not None
    ncols = 2 if has_ecl else 1

    fig, axes = plt.subplots(1, ncols, figsize=(4.8 * ncols, 3.8))
    if ncols == 1:
        axes = [axes]

    _draw_panel(
        axes[0],
        etth1_agg,
        [96, 192, 336, 720],
        "ETTh1 (C=7): CI vs CD",
        ylabel=True,
    )
    if has_ecl:
        ecl_pred_lens = sorted(int(p) for p in ecl_agg["pred_len"].unique())
        ecl_modes = [m for m in ("CI", "CD") if m in set(ecl_agg["mode"])]
        mode_label = " vs ".join(ecl_modes) if len(ecl_modes) > 1 else f"{ecl_modes[0]} only"
        seed_note = ""
        if ecl_seeds is not None and len(ecl_seeds) < 2:
            seed_note = f"\n(seed {ecl_seeds[0]})"
        _draw_panel(
            axes[1],
            ecl_agg,
            ecl_pred_lens,
            f"ECL (C=321): {mode_label}{seed_note}",
            ylabel=False,
        )

    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: {out_path}")


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> int:
    """Run the full ETTh1/ECL/correlation analysis and write the figure.

    Returns:
        0 if the pooled-ETTh1 oracle check passes, 1 otherwise. Structural
        and schema failures elsewhere (bad CSVs, oracle drift in the
        correlation summary) raise directly rather than returning non-zero.
    """
    etth1_path = Path(sys.argv[1]) if len(sys.argv) > 1 else _ETTH1_PATH
    etth1 = load_etth1(etth1_path)
    ecl = load_ecl(_ECL_PATH)
    corr = load_corr_summary(_CORR_PATH)
    lag = load_lag_summary(_LAG_PATH)

    # Compute all aggregations in main; print_* functions receive pre-computed data.
    etth1_seeds = sorted(int(s) for s in etth1["seed"].unique())
    etth1_agg = aggregate_by_mode_horizon(etth1)
    ratio = etth1_ratio_table(etth1)
    paired = etth1_paired_diff(etth1)
    budget = etth1_budget_table(etth1)
    ecl_agg = aggregate_by_mode_horizon(ecl) if ecl is not None else None
    ecl_seeds = sorted(int(s) for s in ecl["seed"].unique()) if ecl is not None else None

    print_etth1_summary(ratio, paired, budget, etth1_seeds)
    pooled = etth1_pooled_diff(etth1)
    passed = print_etth1_pooled(pooled)
    if ecl is not None:
        print_ecl_summary(ecl)
    if corr is not None:
        print_corr_summary(corr, lag)

    plot_real_data(etth1_agg, ecl_agg, ecl_seeds, _FIGURES_DIR / "real_data.png")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())