"""Granger causality validation for the leader-follower VAR(1) experiment.

Purpose
-------
Empirically verifies that the data generated by generate_leader_follower.py has the causal structure its design intends:

  1. AR(1) grid (gamma=0): no Granger causality between any channel pair.
  2. Leader-follower VAR(1) (gamma>0): leader i Granger-causes follower i+10, but not the reverse, and no other
     cross-channel causality is present.

This serves as a direct empirical check on the mechanistic claim in the paper: "in the AR(1) grid, Granger non-causality
holds across all channel pairs by construction; in the leader-follower regime, only the designed leader->follower
directions exhibit Granger causality."

Test design
-----------
We use bivariate VAR(1) F-tests (Granger, 1969) as implemented in statsmodels.tsa.stattools.grangercausalitytests.
The lag order is fixed at 1 because the DGP is VAR(1) by construction.

We test four structural groups:
  (a) All 10 designed leader->follower pairs. Expected: significant for gamma>0, not significant for gamma=0.
  (b) All 10 reverse follower->leader pairs. Expected: not significant at any gamma.
  (c) Five randomly sampled leader->leader pairs. Expected: not significant at any gamma.
  (d) Conditional test: does isolate variate predict followers AFTER conditioning on the true leader? Tests the claim
      that bivariate spurious significance (isolate->follower) is entirely attributable to the omitted leader, as
      expected from omitted-variable theory.

Note on omitted-variable spurious causality
-------------------------------------------
A bivariate test of (isolate -> follower) can appear significant even though the isolate has no structural effect on
followers, because the isolate shares contemporaneous innovation correlation (rho) with leaders, which do structurally
cause followers. This is an expected consequence of the compound-symmetry covariance, not a defect in the generator.
The conditional test in group (d) directly verifies this: once the leader is included as a covariate, the isolate
no longer predicts the follower.

Note on expected false positives in follower->leader tests
----------------------------------------------------------
With 10 bivariate tests at alpha=0.05, approximately 0.4 false positives are expected under the null. At gamma=0.6 and
gamma=0.9, where followers carry more variance from the coupling, a marginal false positive (e.g., p=0.047 for one seed)
is within normal sampling variation. Such cases are seed-specific and do not appear across all five experiment seeds
{42, 123, 456, 789, 1011}.

We do not exhaustively test all C*(C-1) pairs. The purpose is structural validation of the intended mechanism, not a
general causality screen. Exhaustive testing would require Bonferroni or FDR correction and is outside the scope of this
validation.

Output status conventions
-------------------------
Per-group and overall status is one of three values:
  [PASS]     All tests in the group produced the expected outcome.
  [FAIL]     One or more tests produced an unexpected outcome. This indicates a possible defect in the data generator
             and should be investigated.
  [EXPECTED] All failures in the group are in a category where false positives are statistically expected
             (follower->leader or leader->leader at any gamma, or leader->follower at gamma=0). The generator
             is behaving correctly.

The distinction between FAIL and EXPECTED prevents a real generator defect from
being masked by the "expected false positive" explanation, and prevents a
spurious alarm when sampling variation produces the anticipated result. The
conditional isolate->follower tests are deliberately excluded from EXPECTED:
their null is also true, but a false positive there is graded FAIL so the
paper's key conditioning claim is never waved through as sampling noise.

Usage
-----
python validate_granger.py [--gamma GAMMA [GAMMA ...]] [--rho RHO] [--seed SEED]
Default gamma sweep is {0.0, 0.3, 0.6, 0.9} -- all four values used in the
leader-follower experiment. Run from the repository root.

Outputs to console only; no files written.
"""

import argparse
import warnings

import numpy as np
import pandas as pd
from scipy import stats as scipy_stats
from statsmodels.regression.linear_model import OLS
from statsmodels.tools import add_constant
from statsmodels.tsa.stattools import grangercausalitytests

import sys as _sys
from pathlib import Path as _Path

_sys.path.insert(0, str(_Path(__file__).resolve().parents[1] / "generators"))

from generate_leader_follower import (  # noqa: E402  (must follow the sys.path shim above)
    N_FOLLOWERS,
    N_LEADERS,
    _ISOLATE_IDX,
    generate,
)

# statsmodels emits a FutureWarning on every call to grangercausalitytests (verbose is being deprecated) regardless of
# verbose=False
warnings.filterwarnings("ignore", category=FutureWarning, module="statsmodels",)

# Significance threshold for all tests.
_ALPHA: float = 0.05
# VAR lag order matches the true DGP.
_LAG_ORDER: int = 1
# Seed for reproducible leader->leader pair sampling. Kept separate from the data seed so the same five pairs are drawn
# on every run regardless of --seed, making the leader->leader results directly comparable across seeds.
_SAMPLE_SEED: int = 0


def _bivariate_pvalue(data: np.ndarray, cause: int, effect: int) -> float:
    """F-test p-value for 'cause Granger-causes effect' at lag 1 (bivariate).

    Args:
        data:   Array of shape (T, C).
        cause:  Column index of the putative cause variable.
        effect: Column index of the putative effect variable.

    Returns:
        p-value from the Granger F-test.
    """
    pair = np.column_stack([data[:, effect], data[:, cause]])
    try:
        results = grangercausalitytests(pair, maxlag=_LAG_ORDER, verbose=False)
    except TypeError:  # statsmodels release that removed the deprecated verbose kwarg
        results = grangercausalitytests(pair, maxlag=_LAG_ORDER)
    return float(results[_LAG_ORDER][0]["ssr_ftest"][1])


def _conditional_pvalue(data: np.ndarray, cause: int, effect: int, controls: list[int],) -> float:
    """F-test p-value for 'cause -> effect' conditional on control variables.

    Tests whether lagged cause[t-1] improves prediction of effect[t] after controlling for lagged effect[t-1] and lagged
    controls[t-1].

    Args:
        data:     Array of shape (T, C).
        cause:    Column index of the putative cause.
        effect:   Column index of the response variable.
        controls: Column indices to condition on.

    Returns:
        p-value from the incremental F-test.
    """
    y = data[1:, effect]
    base_cols = [effect] + controls
    X_restricted = data[:-1, base_cols]
    X_unrestricted = np.column_stack([X_restricted, data[:-1, cause]])

    r_res = OLS(y, add_constant(X_restricted)).fit()
    r_unr = OLS(y, add_constant(X_unrestricted)).fit()

    n = len(y)
    k_res = X_restricted.shape[1] + 1
    k_unr = X_unrestricted.shape[1] + 1
    F = ((r_res.ssr - r_unr.ssr) / (k_unr - k_res)) / (r_unr.ssr / (n - k_unr))
    return float(scipy_stats.f.sf(F, k_unr - k_res, n - k_unr))


def _run_tests(data: np.ndarray, gamma: float, rng: np.random.Generator,) -> pd.DataFrame:
    """Run the structured Granger test battery.

    Args:
        data:  Array of shape (T, C_TOTAL).
        gamma: Coupling strength (for labelling expectations).
        rng:   Random generator for pair sampling.

    Returns:
        DataFrame with one row per test.
    """
    rows: list[dict] = []

    def record(direction: str, cause: int, effect: int, pvalue: float, expected: bool,) -> None:
        rows.append(
            {
                "direction": direction,
                "cause": cause,
                "effect": effect,
                "pvalue": round(pvalue, 4),
                "significant": pvalue < _ALPHA,
                "expected_significant": expected,
                "correct": (pvalue < _ALPHA) == expected,
            }
        )

    # (a) All 10 designed leader->follower pairs (bivariate).
    expected_lf = gamma > 0.0
    for k in range(N_FOLLOWERS):
        pval = _bivariate_pvalue(data, cause=k, effect=N_LEADERS + k)
        record("leader->follower (bivariate)", k, N_LEADERS + k, pval, expected_lf)

    # (b) All 10 reverse follower->leader pairs (bivariate).
    for k in range(N_FOLLOWERS):
        pval = _bivariate_pvalue(data, cause=N_LEADERS + k, effect=k)
        record("follower->leader (bivariate)", N_LEADERS + k, k, pval, False)

    # (c) Five randomly sampled leader->leader pairs (bivariate).
    sampled: set[tuple[int, int]] = set()
    while len(sampled) < 5:
        i, j = int(rng.integers(N_LEADERS)), int(rng.integers(N_LEADERS))
        if i != j and (i, j) not in sampled:
            sampled.add((i, j))
            pval = _bivariate_pvalue(data, cause=i, effect=j)
            record("leader->leader (bivariate)", i, j, pval, False)

    # (d) Conditional test: isolate->follower after conditioning on true leader.
    # Tests followers 10 and 17 (the first and eighth follower pairs: leaders 0 and 7). These are representative, not
    # randomly sampled: the same two pairs are always tested so results are reproducible and comparable across seeds.
    # Expected: NOT significant (isolate has no structural effect once the true leader is controlled for).
    for k in [0, 7]:  # representative follower pairs (leader k, follower k+10)
        follower = N_LEADERS + k
        leader = k
        pval = _conditional_pvalue(data, cause=_ISOLATE_IDX, effect=follower, controls=[leader])
        record(
            f"isolate->follower{follower} | leader{leader} (conditional)",
            _ISOLATE_IDX,
            follower,
            pval,
            expected=False,
        )

    return pd.DataFrame(rows)


def _is_expected_failure(row: pd.Series, gamma: float) -> bool:
    """True when a test failure is statistically expected rather than indicative of a generator defect.

    Expected failures are false positives (significant when not expected) in groups where the null is true:
    follower->leader, leader->leader, or leader->follower at gamma=0. A genuine failure is a false negative
    (non-significant when expected) in the leader->follower group at gamma > 0, which would indicate the generator is
    not producing the designed coupling.
    """
    is_false_positive = row["significant"] and not row["expected_significant"]
    in_null_group = (
        "follower->leader" in row["direction"]
        or "leader->leader" in row["direction"]
        or ("leader->follower" in row["direction"] and gamma == 0.0)
    )
    return bool(is_false_positive and in_null_group)


def run_validation(gamma: float, rho: float, seed: int) -> None:
    """Generate data and run the full Granger test battery."""
    print(f"\n{'='*64}")
    print(f"Granger validation: gamma={gamma}, rho={rho}, seed={seed}")
    print(f"Lag order: {_LAG_ORDER}  |  Alpha: {_ALPHA}")
    print(f"{'='*64}")

    data = generate(phi=0.8, gamma=gamma, rho=rho, seed=seed)
    rng = np.random.default_rng(_SAMPLE_SEED)
    results = _run_tests(data, gamma, rng)

    for direction, grp in results.groupby("direction", sort=False):
        n_total = len(grp)
        n_correct = int(grp["correct"].sum())
        n_sig = int(grp["significant"].sum())
        expected = grp["expected_significant"].iloc[0]

        if n_correct == n_total:
            status = "PASS"
        else:
            failures = grp[~grp["correct"]]
            all_expected = all(_is_expected_failure(r, gamma) for _, r in failures.iterrows())
            status = "EXPECTED" if all_expected else "FAIL"

        print(f"\n[{status}] {direction}")
        print(
            f"  Expected: {'significant' if expected else 'not significant'}  |  "
            f"{n_correct}/{n_total} correct  |  {n_sig} significant"
        )
        for _, r in grp.iterrows():
            marker = "\u2713" if r["correct"] else "\u2717"
            print(
                f"  {marker}  {r['cause']:>2} -> {r['effect']:>2}  "
                f"p={r['pvalue']:.4f}  {'*' if r['significant'] else ' '}"
            )

    # Overall status: FAIL only if any failure is not an expected false positive.
    all_failures = results[~results["correct"]]
    if all_failures.empty:
        overall = "PASS"
    elif all(_is_expected_failure(r, gamma) for _, r in all_failures.iterrows()):
        overall = "EXPECTED"
    else:
        overall = "FAIL"

    n_total = len(results)
    n_correct = int(results["correct"].sum())
    print(f"\n{'─'*40}")
    print(f"Overall: {n_correct}/{n_total} tests correct  [{overall}]")

    if overall == "EXPECTED":
        print(
            "  Note: all failures are false positives in null-hypothesis groups "
            "(follower->leader or leader->leader). This is expected sampling "
            "variation at alpha=0.05 and does not indicate a generator defect."
        )
    elif overall == "FAIL":
        genuine = all_failures[~all_failures.apply(lambda r: _is_expected_failure(r, gamma), axis=1)]
        cols = ["direction", "cause", "effect", "pvalue", "significant", "expected_significant"]
        print("\nGenuine failures (unexpected outcome -- investigate generator):")
        print(genuine[cols].to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate Granger causality structure of generated data.")
    parser.add_argument("--gamma", type=float, nargs="+", default=[0.0, 0.3, 0.6, 0.9],
                        help="Gamma values to validate (default: 0.0 0.3 0.6 0.9).",)
    parser.add_argument("--rho", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    for gamma in args.gamma:
        run_validation(gamma=gamma, rho=args.rho, seed=args.seed)


if __name__ == "__main__":
    main()